# Form implementation generated from reading ui file '/Users/rossharvey/Documents/SoftwareDevelopment/galvanic/galvanic/src/galvanic/ui/register_map/forms/field.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(422, 70)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.field_name_label = QtWidgets.QLabel(parent=self.frame)
        self.field_name_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.field_name_label.setObjectName("field_name_label")
        self.verticalLayout.addWidget(self.field_name_label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.value_lineedit = QtWidgets.QLineEdit(parent=self.frame)
        self.value_lineedit.setMinimumSize(QtCore.QSize(200, 0))
        self.value_lineedit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.value_lineedit.setObjectName("value_lineedit")
        self.horizontalLayout_2.addWidget(self.value_lineedit)
        self.value_combobox = QtWidgets.QComboBox(parent=self.frame)
        self.value_combobox.setMinimumSize(QtCore.QSize(200, 0))
        self.value_combobox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.value_combobox.setObjectName("value_combobox")
        self.horizontalLayout_2.addWidget(self.value_combobox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.field_name_label.setText(_translate("Form", "{field_name}"))
