# Form implementation generated from reading ui file '/Users/rossharvey/Documents/SoftwareDevelopment/galvanic/galvanic/src/galvanic/ui/register_map/forms/register_map.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1381, 453)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.register_map_scrollarea = QtWidgets.QScrollArea(parent=Form)
        self.register_map_scrollarea.setWidgetResizable(True)
        self.register_map_scrollarea.setObjectName("register_map_scrollarea")
        self.register_map_scrollarea_contents = QtWidgets.QWidget()
        self.register_map_scrollarea_contents.setGeometry(QtCore.QRect(0, 0, 1369, 441))
        self.register_map_scrollarea_contents.setObjectName("register_map_scrollarea_contents")
        self.register_map_scrollarea_layout = QtWidgets.QVBoxLayout(self.register_map_scrollarea_contents)
        self.register_map_scrollarea_layout.setObjectName("register_map_scrollarea_layout")
        self.register_map_scrollarea.setWidget(self.register_map_scrollarea_contents)
        self.horizontalLayout.addWidget(self.register_map_scrollarea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
