# Form implementation generated from reading ui file '/Users/rossharvey/Documents/SoftwareDevelopment/galvanic/galvanic/src/galvanic/ui/register_map/forms/register_map.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(910, 343)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.register_map_frame = QtWidgets.QFrame(parent=Form)
        self.register_map_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.register_map_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.register_map_frame.setObjectName("register_map_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.register_map_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout.addWidget(self.register_map_frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
