# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: io_commands/pin_enums.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'io_commands/pin_enums.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bio_commands/pin_enums.proto\x12\x15\x65mbedded_design_tools*+\n\x08Polarity\x12\x0e\n\nACTIVE_LOW\x10\x00\x12\x0f\n\x0b\x41\x43TIVE_HIGH\x10\x01* \n\x0bOutputValue\x12\x07\n\x03LOW\x10\x00\x12\x08\n\x04HIGH\x10\x01*&\n\tValueType\x12\x0c\n\x08PHYSICAL\x10\x00\x12\x0b\n\x07LOGICAL\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'io_commands.pin_enums_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POLARITY']._serialized_start=54
  _globals['_POLARITY']._serialized_end=97
  _globals['_OUTPUTVALUE']._serialized_start=99
  _globals['_OUTPUTVALUE']._serialized_end=131
  _globals['_VALUETYPE']._serialized_start=133
  _globals['_VALUETYPE']._serialized_end=171
# @@protoc_insertion_point(module_scope)
