# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: io_commands/pwm.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'io_commands/pwm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from io_commands import pin_enums_pb2 as io__commands_dot_pin__enums__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15io_commands/pwm.proto\x12\x15\x65mbedded_design_tools\x1a\x1bio_commands/pin_enums.proto\"\x81\x02\n\x05PwmIn\x12\x13\n\tpad_index\x18\x01 \x01(\rH\x00\x12\x12\n\x08pad_name\x18\x02 \x01(\tH\x00\x12\x12\n\x08pin_name\x18\x03 \x01(\tH\x00\x12\x15\n\x08polarity\x18\x04 \x01(\rH\x01\x88\x01\x01\x12\x39\n\nvalue_type\x18\x05 \x01(\x0e\x32 .embedded_design_tools.ValueTypeH\x02\x88\x01\x01\x12@\n\x10measurement_type\x18\x06 \x01(\x0e\x32&.embedded_design_tools.MeasurementTypeB\x0b\n\tTargetPadB\x0b\n\t_polarityB\r\n\x0b_value_type\"\x93\x02\n\x06PwmOut\x12\x13\n\tpad_index\x18\x01 \x01(\rH\x00\x12\x12\n\x08pad_name\x18\x02 \x01(\tH\x00\x12\x12\n\x08pin_name\x18\x03 \x01(\tH\x00\x12\x15\n\x08polarity\x18\x04 \x01(\rH\x01\x88\x01\x01\x12\x39\n\nvalue_type\x18\x05 \x01(\x0e\x32 .embedded_design_tools.ValueTypeH\x02\x88\x01\x01\x12;\n\x0boutput_type\x18\x06 \x01(\x0e\x32&.embedded_design_tools.MeasurementType\x12\x14\n\x0coutput_value\x18\x07 \x01(\x02\x42\x0b\n\tTargetPadB\x0b\n\t_polarityB\r\n\x0b_value_type*L\n\x0fMeasurementType\x12\r\n\tFREQUENCY\x10\x00\x12\x08\n\x04\x44UTY\x10\x01\x12\x0f\n\x0bPULSE_WIDTH\x10\x02\x12\x0f\n\x0bPULSE_COUNT\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'io_commands.pwm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEASUREMENTTYPE']._serialized_start=615
  _globals['_MEASUREMENTTYPE']._serialized_end=691
  _globals['_PWMIN']._serialized_start=78
  _globals['_PWMIN']._serialized_end=335
  _globals['_PWMOUT']._serialized_start=338
  _globals['_PWMOUT']._serialized_end=613
# @@protoc_insertion_point(module_scope)
