# Form implementation generated from reading ui file '/Users/rossharvey/Documents/SoftwareDevelopment/galvanic/galvanic/src/galvanic/ui/register_map/forms/register_map.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1426, 517)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinAndMaxSize)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.register_map_scrollarea = QtWidgets.QScrollArea(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.register_map_scrollarea.sizePolicy().hasHeightForWidth())
        self.register_map_scrollarea.setSizePolicy(sizePolicy)
        self.register_map_scrollarea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.register_map_scrollarea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.register_map_scrollarea.setWidgetResizable(True)
        self.register_map_scrollarea.setObjectName("register_map_scrollarea")
        self.register_map_scrollarea_contents = QtWidgets.QWidget()
        self.register_map_scrollarea_contents.setGeometry(QtCore.QRect(0, 0, 24, 505))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.register_map_scrollarea_contents.sizePolicy().hasHeightForWidth())
        self.register_map_scrollarea_contents.setSizePolicy(sizePolicy)
        self.register_map_scrollarea_contents.setObjectName("register_map_scrollarea_contents")
        self.register_map_scrollarea_layout = QtWidgets.QVBoxLayout(self.register_map_scrollarea_contents)
        self.register_map_scrollarea_layout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinAndMaxSize)
        self.register_map_scrollarea_layout.setObjectName("register_map_scrollarea_layout")
        self.register_map_scrollarea.setWidget(self.register_map_scrollarea_contents)
        self.horizontalLayout.addWidget(self.register_map_scrollarea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
