# Form implementation generated from reading ui file '/Users/rossharvey/Documents/SoftwareDevelopment/galvanic/galvanic/src/galvanic/ui/register_map/forms/register.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(222, 41)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.register_groupbox = QtWidgets.QGroupBox(parent=Form)
        self.register_groupbox.setObjectName("register_groupbox")
        self.register_layout = QtWidgets.QHBoxLayout(self.register_groupbox)
        self.register_layout.setContentsMargins(2, 2, 2, 2)
        self.register_layout.setSpacing(1)
        self.register_layout.setObjectName("register_layout")
        self.horizontalLayout.addWidget(self.register_groupbox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.register_groupbox.setTitle(_translate("Form", "{register_name}"))
